App.setTheme("b", {

"--btnhlp-color" : "var(--body-viewcolor)",
"--btnhlp-ivcolor" : "var(--body-viewbg)",
"--btnhlp-colorhover" : "var(--body-viewhover)",
"--btnhlp-ivcolorhover" : "var(--body-viewhover)",
"--btnhlp-size" : "2rem",

"--bar-panel-bg":"var(--paper-grey-50)",
"--bar-panel-color":"black",
"--bar-panel-hover":"var(--paper-grey-400)",
"--bar-panel-padding": "0.1rem 0.5rem 0.5rem 0.5rem",
"--bar-panelsep-color": "var(--paper-grey-300)",
"--bar-panelsep-margin": "0 1rem",
"--bar-panelsep-h": "2px",

"--bar-panelbtn1-color": "var(--paper-grey-700)",
"--bar-panelbtn1-colorhover": "var(--bar-panel-hover)",
"--bar-panelbtn1-bg": "none",
"--bar-panelbtn1-bghover": "none",
"--bar-panelbtn1-colordis": "var(--paper-grey-300)",

"--bar-panel-bg":"white",
"--bar-panel-color":"black",
"--bar-panel-hover":"var(--paper-grey-400)",
"--bar-panel-padding": "0",
"--bar-panelsep-color": "var(--paper-indigo-200)",
"--bar-panelsep-margin": "0",
"--bar-panelsep-h": "2px",

"--bar-panelbtn1-color": "var(--paper-indigo-700)",
"--bar-panelbtn1-colorhover": "var(--bar-panel-hover)",
"--bar-panelbtn1-bg": "none",
"--bar-panelbtn1-bghover": "none",
"--bar-panelbtn1-colordis": "var(--paper-indigo-200)",

"--body-panel-bg":"var(--paper-grey-50)",
"--body-panel-color":"black",
"--body-panel-hover":"var(--paper-grey-400)",

"--bar-view0-bg":"white",
"--bar-view1-bg":"white",
"--bar-view2-bg":"white",
"--bar-view0-color":"var(--paper-grey-800)",
"--bar-view1-color":"var(--paper-indigo-800)",
"--bar-view2-color":"var(--paper-teal-800)",
"--bar-view-hover":"var(--paper-grey-400)",
"--bar-view-colordis":"var(--paper-grey-300)",
"--bar-view-padding": "0.1rem 0.3rem",
"--bar-view0sep-color": "var(--paper-grey-400)",
"--bar-view1sep-color": "var(--paper-indigo-400)",
"--bar-view2sep-color": "var(--paper-teal-400)",
"--bar-viewsep-margin": "0 1rem 0.2rem 1rem",
"--bar-viewsep-h": "2px",
"--bar-view-mitemsep":"var(--paper-grey-100)",
"--bar-view-mitembg":"white",
"--bar-view-menubg":"var(--paper-grey-50)",
"--bar-view-menucolor":"var(--paper-grey-700)",

"--bar-view0btn1-color": "var(--paper-grey-800)",
"--bar-view0btn1-coloriv": "var(--paper-grey-800)",
"--bar-view0btn1-colorhover": "var(--paper-grey-800)",
"--bar-view0btn1-bg": "white",
"--bar-view0btn1-bgiv": "white",
"--bar-view0btn1-bghover": "var(--bar-view-hover)",
"--bar-view0btn1-colordis": "var(--paper-grey-300)",

"--bar-view1btn1-color": "var(--paper-indigo-800)",
"--bar-view1btn1-colorhover": "var(--paper-indigo-800)",
"--bar-view1btn1-bg": "white",
"--bar-view1btn1-bghover": "var(--bar-view-hover)",
"--bar-view1btn1-colordis": "var(--paper-indigo-300)",

"--bar-view2btn1-color": "var(--paper-teal-800)",
"--bar-view2btn1-colorhover": "var(--paper-teal-800)",
"--bar-view2btn1-bg": "white",
"--bar-view2btn1-bghover": "var(--bar-view-hover)",
"--bar-view2btn1-colordis": "var(--paper-teal-300)",


"--body-panelbg":"var(--paper-grey-50)",
"--body-panelcolor":"black",
"--body-panelhover":"var(--paper-grey-400)",

});